MODULE DOMAIN

  IMPLICIT NONE
  !WRF MODEL
  INTEGER, PARAMETER     :: NT = 73, NY = 384, NX = 384, NDIMS = 3
  INTEGER                :: NHOR = NT*NY*NX
  INTEGER, PARAMETER     :: BOTTOM_TOP_STAG = 30
  INTEGER, PARAMETER     :: BOTTOM_TOP = 29
  INTEGER, PARAMETER     :: SOIL_LAYERS_STAG = 4
  !GFS
  INTEGER, PARAMETER     :: NTGFS = 10, NYGFS = 721, NXGFS = 1440
  !CONWX
  INTEGER, PARAMETER     :: NTCWX = 180, NYCWX = 427, NXCWX = 493

END MODULE DOMAIN
